// Generated by pnpm docs:generate-metadata. Do not edit by hand.
import { type ComponentDocSlug } from './component-docs.registry';

export interface ComponentApiInputMetadata {
  readonly name: string;
  readonly type: string;
  readonly defaultValue: string;
  readonly required: boolean;
  readonly description?: string;
}

export interface ComponentApiOutputMetadata {
  readonly name: string;
  readonly type: string;
  readonly description?: string;
}

export interface ComponentApiSymbolMetadata {
  readonly name: string;
  readonly selectors: readonly string[];
  readonly exportAs?: string;
  readonly inputs: readonly ComponentApiInputMetadata[];
  readonly outputs: readonly ComponentApiOutputMetadata[];
  readonly sourcePath: string;
}

export interface ComponentApiMetadata {
  readonly selectors: readonly string[];
  readonly exports: readonly string[];
  readonly inputs: readonly string[];
  readonly outputs: readonly string[];
  readonly sourcePaths: readonly string[];
  readonly symbols: readonly ComponentApiSymbolMetadata[];
}

export const componentApiMetadata = {
  conversation: {
    selectors: [
      'ai-conversation',
      '[aiConversation]',
      '[aiConversationContent]',
      'ai-conversation-content',
      '[aiConversationScrollAnchor]',
    ],
    exports: ['Conversation', 'ConversationContent', 'ConversationScrollAnchor'],
    inputs: ['stickToBottom', 'class'],
    outputs: [],
    sourcePaths: [
      'projects/duxkit-ai/src/lib/conversation/conversation.ts',
      'projects/duxkit-ai/src/lib/conversation/conversation-content.ts',
      'projects/duxkit-ai/src/lib/conversation/conversation-scroll-anchor.ts',
    ],
    symbols: [
      {
        name: 'Conversation',
        selectors: ['ai-conversation', '[aiConversation]'],
        inputs: [
          {
            name: 'stickToBottom',
            type: "'auto' | boolean",
            defaultValue: "'auto'",
            required: false,
            description: 'Controls whether the conversation content scrolls to the latest message.',
          },
          {
            name: 'class',
            type: 'string | undefined',
            defaultValue: 'undefined',
            required: false,
            description: 'Additional classes merged onto the conversation root element.',
          },
        ],
        outputs: [],
        sourcePath: 'projects/duxkit-ai/src/lib/conversation/conversation.ts',
      },
      {
        name: 'ConversationContent',
        selectors: ['[aiConversationContent]', 'ai-conversation-content'],
        inputs: [
          {
            name: 'class',
            type: 'string | undefined',
            defaultValue: 'undefined',
            required: false,
            description:
              'Additional classes merged onto the scrollable conversation content element.',
          },
        ],
        outputs: [],
        sourcePath: 'projects/duxkit-ai/src/lib/conversation/conversation-content.ts',
      },
      {
        name: 'ConversationScrollAnchor',
        selectors: ['[aiConversationScrollAnchor]'],
        exportAs: 'aiConversationAnchor',
        inputs: [],
        outputs: [],
        sourcePath: 'projects/duxkit-ai/src/lib/conversation/conversation-scroll-anchor.ts',
      },
    ],
  },
  message: {
    selectors: [
      'ai-message',
      '[aiMessage]',
      'ai-message-content',
      '[aiMessageContent]',
      'ai-message-actions',
      '[aiMessageActions]',
      'ai-message-actions-copy',
      'ai-message-actions-thumbs-up',
      'ai-message-actions-thumbs-down',
    ],
    exports: [
      'Message',
      'MessageContent',
      'MessageActions',
      'MessageActionsCopy',
      'MessageActionsThumbsUp',
      'MessageActionsThumbsDown',
    ],
    inputs: ['from', 'class', 'markdown', 'text', 'active'],
    outputs: ['copiedChange', 'thumbsUp', 'thumbsDown'],
    sourcePaths: [
      'projects/duxkit-ai/src/lib/message/message.ts',
      'projects/duxkit-ai/src/lib/message/message-content.ts',
      'projects/duxkit-ai/src/lib/message/message-actions.ts',
    ],
    symbols: [
      {
        name: 'Message',
        selectors: ['ai-message', '[aiMessage]'],
        inputs: [
          {
            name: 'from',
            type: "UIMessage['role']",
            defaultValue: '-',
            required: true,
            description: 'Role used to style and identify the message in the conversation.',
          },
          {
            name: 'class',
            type: 'string | undefined',
            defaultValue: 'undefined',
            required: false,
            description: 'Additional classes merged onto the message root element.',
          },
        ],
        outputs: [],
        sourcePath: 'projects/duxkit-ai/src/lib/message/message.ts',
      },
      {
        name: 'MessageContent',
        selectors: ['ai-message-content', '[aiMessageContent]'],
        inputs: [
          {
            name: 'markdown',
            type: 'string | undefined',
            defaultValue: 'undefined',
            required: false,
            description: 'Markdown source rendered as rich message content.',
          },
          {
            name: 'class',
            type: 'string | undefined',
            defaultValue: 'undefined',
            required: false,
            description: 'Additional classes merged onto the message content element.',
          },
        ],
        outputs: [],
        sourcePath: 'projects/duxkit-ai/src/lib/message/message-content.ts',
      },
      {
        name: 'MessageActions',
        selectors: ['ai-message-actions', '[aiMessageActions]'],
        inputs: [
          {
            name: 'class',
            type: 'string | undefined',
            defaultValue: 'undefined',
            required: false,
            description: 'Additional classes merged onto the message actions group.',
          },
        ],
        outputs: [],
        sourcePath: 'projects/duxkit-ai/src/lib/message/message-actions.ts',
      },
      {
        name: 'MessageActionsCopy',
        selectors: ['ai-message-actions-copy'],
        inputs: [
          {
            name: 'text',
            type: 'string | undefined',
            defaultValue: 'undefined',
            required: false,
            description:
              'Text copied by the action; falls back to registered message content when omitted.',
          },
        ],
        outputs: [
          {
            name: 'copiedChange',
            type: 'string',
            description: 'Emits the copied text after a successful copy action.',
          },
        ],
        sourcePath: 'projects/duxkit-ai/src/lib/message/message-actions.ts',
      },
      {
        name: 'MessageActionsThumbsUp',
        selectors: ['ai-message-actions-thumbs-up'],
        inputs: [
          {
            name: 'active',
            type: 'boolean',
            defaultValue: 'false',
            required: false,
            description: 'Whether the thumbs up action is currently selected.',
          },
        ],
        outputs: [
          {
            name: 'thumbsUp',
            type: 'void',
            description: 'Emits when the thumbs up action is pressed.',
          },
        ],
        sourcePath: 'projects/duxkit-ai/src/lib/message/message-actions.ts',
      },
      {
        name: 'MessageActionsThumbsDown',
        selectors: ['ai-message-actions-thumbs-down'],
        inputs: [
          {
            name: 'active',
            type: 'boolean',
            defaultValue: 'false',
            required: false,
            description: 'Whether the thumbs down action is currently selected.',
          },
        ],
        outputs: [
          {
            name: 'thumbsDown',
            type: 'void',
            description: 'Emits when the thumbs down action is pressed.',
          },
        ],
        sourcePath: 'projects/duxkit-ai/src/lib/message/message-actions.ts',
      },
    ],
  },
  attachment: {
    selectors: [
      '[aiAttachment]',
      'ai-attachment',
      '[aiAttachmentPreview]',
      'ai-attachment-preview',
      'button[aiAttachmentRemove]',
      'ai-attachment-remove',
      '[aiAttachments]',
      'ai-attachments',
    ],
    exports: ['Attachment', 'AttachmentPreview', 'AttachmentRemove', 'Attachments'],
    inputs: ['data', 'class', 'ariaLabel', 'variant'],
    outputs: ['removed'],
    sourcePaths: [
      'projects/duxkit-ai/src/lib/attachment/attachment.ts',
      'projects/duxkit-ai/src/lib/attachment/attachment-preview.ts',
      'projects/duxkit-ai/src/lib/attachment/attachment-remove.ts',
      'projects/duxkit-ai/src/lib/attachment/attachments.ts',
    ],
    symbols: [
      {
        name: 'Attachment',
        selectors: ['[aiAttachment]', 'ai-attachment'],
        inputs: [
          {
            name: 'data',
            type: 'AiAttachmentPart',
            defaultValue: '-',
            required: true,
            description: 'AI SDK file or source-document part rendered by this attachment.',
          },
          {
            name: 'class',
            type: 'string | undefined',
            defaultValue: 'undefined',
            required: false,
            description: 'Additional classes merged onto the attachment root element.',
          },
        ],
        outputs: [
          {
            name: 'removed',
            type: 'AiAttachmentPart',
            description: 'Emits the current attachment part when the remove control is pressed.',
          },
        ],
        sourcePath: 'projects/duxkit-ai/src/lib/attachment/attachment.ts',
      },
      {
        name: 'AttachmentPreview',
        selectors: ['[aiAttachmentPreview]', 'ai-attachment-preview'],
        inputs: [
          {
            name: 'class',
            type: 'string | undefined',
            defaultValue: 'undefined',
            required: false,
            description: 'Additional classes merged onto the attachment preview element.',
          },
        ],
        outputs: [],
        sourcePath: 'projects/duxkit-ai/src/lib/attachment/attachment-preview.ts',
      },
      {
        name: 'AttachmentRemove',
        selectors: ['button[aiAttachmentRemove]', 'ai-attachment-remove'],
        inputs: [
          {
            name: 'ariaLabel',
            type: 'string | undefined',
            defaultValue: 'undefined',
            required: false,
            description: 'Accessible label for the remove button.',
          },
          {
            name: 'class',
            type: 'string | undefined',
            defaultValue: 'undefined',
            required: false,
            description: 'Additional classes merged onto the attachment remove control.',
          },
        ],
        outputs: [],
        sourcePath: 'projects/duxkit-ai/src/lib/attachment/attachment-remove.ts',
      },
      {
        name: 'Attachments',
        selectors: ['[aiAttachments]', 'ai-attachments'],
        inputs: [
          {
            name: 'variant',
            type: 'AttachmentsVariant',
            defaultValue: "'grid'",
            required: false,
            description: 'Display layout used by projected attachment items.',
          },
          {
            name: 'class',
            type: 'string | undefined',
            defaultValue: 'undefined',
            required: false,
            description: 'Additional classes merged onto the attachment collection.',
          },
        ],
        outputs: [],
        sourcePath: 'projects/duxkit-ai/src/lib/attachment/attachments.ts',
      },
    ],
  },
  'chain-of-thought': {
    selectors: [
      '[aiChainOfThought]',
      'ai-chain-of-thought',
      '[aiChainOfThoughtContent]',
      'ai-chain-of-thought-content',
      'button[aiChainOfThoughtTrigger]',
      'ai-chain-of-thought-trigger',
      '[aiChainOfThoughtImage]',
      'ai-chain-of-thought-image',
      '[aiChainOfThoughtSearchResult]',
      'ai-chain-of-thought-search-result',
      '[aiChainOfThoughtSearchResults]',
      'ai-chain-of-thought-search-results',
      '[aiChainOfThoughtStep]',
      'ai-chain-of-thought-step',
    ],
    exports: [
      'ChainOfThought',
      'ChainOfThoughtContent',
      'ChainOfThoughtTrigger',
      'ChainOfThoughtImage',
      'ChainOfThoughtSearchResult',
      'ChainOfThoughtSearchResults',
      'ChainOfThoughtStep',
    ],
    inputs: [
      'autoToggle',
      'isStreaming',
      'class',
      'caption',
      'icon',
      'label',
      'description',
      'status',
      'collapsedMaxHeight',
      'pinToBottom',
      'showMoreLabel',
      'showLessLabel',
    ],
    outputs: [],
    sourcePaths: [
      'projects/duxkit-ai/src/lib/chain-of-thought/chain-of-thought.ts',
      'projects/duxkit-ai/src/lib/chain-of-thought/chain-of-thought-content.ts',
      'projects/duxkit-ai/src/lib/chain-of-thought/chain-of-thought-trigger.ts',
      'projects/duxkit-ai/src/lib/chain-of-thought/chain-of-thought-image.ts',
      'projects/duxkit-ai/src/lib/chain-of-thought/chain-of-thought-search-result.ts',
      'projects/duxkit-ai/src/lib/chain-of-thought/chain-of-thought-search-results.ts',
      'projects/duxkit-ai/src/lib/chain-of-thought/chain-of-thought-step.ts',
    ],
    symbols: [
      {
        name: 'ChainOfThought',
        selectors: ['[aiChainOfThought]', 'ai-chain-of-thought'],
        inputs: [
          {
            name: 'autoToggle',
            type: 'boolean',
            defaultValue: 'true',
            required: false,
            description:
              'Automatically expands while chain-of-thought work is streaming and collapses when it finishes.',
          },
          {
            name: 'isStreaming',
            type: 'boolean',
            defaultValue: 'false',
            required: false,
            description: 'Whether chain-of-thought work is currently streaming.',
          },
          {
            name: 'class',
            type: 'string | undefined',
            defaultValue: 'undefined',
            required: false,
            description: 'Additional classes merged onto the chain-of-thought root element.',
          },
        ],
        outputs: [],
        sourcePath: 'projects/duxkit-ai/src/lib/chain-of-thought/chain-of-thought.ts',
      },
      {
        name: 'ChainOfThoughtContent',
        selectors: ['[aiChainOfThoughtContent]', 'ai-chain-of-thought-content'],
        inputs: [
          {
            name: 'class',
            type: 'string | undefined',
            defaultValue: 'undefined',
            required: false,
            description:
              'Additional classes merged onto the collapsible chain-of-thought content region.',
          },
        ],
        outputs: [],
        sourcePath: 'projects/duxkit-ai/src/lib/chain-of-thought/chain-of-thought-content.ts',
      },
      {
        name: 'ChainOfThoughtTrigger',
        selectors: ['button[aiChainOfThoughtTrigger]', 'ai-chain-of-thought-trigger'],
        inputs: [
          {
            name: 'class',
            type: 'string | undefined',
            defaultValue: 'undefined',
            required: false,
            description: 'Additional classes merged onto the chain-of-thought trigger button.',
          },
        ],
        outputs: [],
        sourcePath: 'projects/duxkit-ai/src/lib/chain-of-thought/chain-of-thought-trigger.ts',
      },
      {
        name: 'ChainOfThoughtImage',
        selectors: ['[aiChainOfThoughtImage]', 'ai-chain-of-thought-image'],
        inputs: [
          {
            name: 'caption',
            type: 'string | undefined',
            defaultValue: 'undefined',
            required: false,
            description: 'Optional caption rendered below the image content.',
          },
          {
            name: 'class',
            type: 'string | undefined',
            defaultValue: 'undefined',
            required: false,
            description: 'Additional classes merged onto the image wrapper element.',
          },
        ],
        outputs: [],
        sourcePath: 'projects/duxkit-ai/src/lib/chain-of-thought/chain-of-thought-image.ts',
      },
      {
        name: 'ChainOfThoughtSearchResult',
        selectors: ['[aiChainOfThoughtSearchResult]', 'ai-chain-of-thought-search-result'],
        inputs: [
          {
            name: 'class',
            type: 'string | undefined',
            defaultValue: 'undefined',
            required: false,
            description: 'Additional classes merged onto the search result token element.',
          },
        ],
        outputs: [],
        sourcePath: 'projects/duxkit-ai/src/lib/chain-of-thought/chain-of-thought-search-result.ts',
      },
      {
        name: 'ChainOfThoughtSearchResults',
        selectors: ['[aiChainOfThoughtSearchResults]', 'ai-chain-of-thought-search-results'],
        inputs: [
          {
            name: 'class',
            type: 'string | undefined',
            defaultValue: 'undefined',
            required: false,
            description: 'Additional classes merged onto the search results container.',
          },
        ],
        outputs: [],
        sourcePath:
          'projects/duxkit-ai/src/lib/chain-of-thought/chain-of-thought-search-results.ts',
      },
      {
        name: 'ChainOfThoughtStep',
        selectors: ['[aiChainOfThoughtStep]', 'ai-chain-of-thought-step'],
        inputs: [
          {
            name: 'icon',
            type: 'string',
            defaultValue: "'lucideDot'",
            required: false,
            description: 'Lucide icon name shown beside the step.',
          },
          {
            name: 'label',
            type: 'string | undefined',
            defaultValue: 'undefined',
            required: false,
            description: 'Primary step label.',
          },
          {
            name: 'description',
            type: 'string | undefined',
            defaultValue: 'undefined',
            required: false,
            description: 'Secondary text shown below the step label.',
          },
          {
            name: 'status',
            type: 'ChainOfThoughtStepStatus',
            defaultValue: "'complete'",
            required: false,
            description: 'Visual status used to style the step marker.',
          },
          {
            name: 'collapsedMaxHeight',
            type: 'number | string | undefined',
            defaultValue: 'undefined',
            required: false,
            description: 'Maximum collapsed content height before the show more control appears.',
          },
          {
            name: 'pinToBottom',
            type: 'boolean',
            defaultValue: 'false',
            required: false,
            description: 'Keeps step content scrolled to the bottom when new content is appended.',
          },
          {
            name: 'showMoreLabel',
            type: 'string',
            defaultValue: "'Show more'",
            required: false,
            description: 'Accessible label for the control that expands clipped step content.',
          },
          {
            name: 'showLessLabel',
            type: 'string',
            defaultValue: "'Show less'",
            required: false,
            description: 'Accessible label for the control that collapses clipped step content.',
          },
          {
            name: 'class',
            type: 'string | undefined',
            defaultValue: 'undefined',
            required: false,
            description: 'Additional classes merged onto the step root element.',
          },
        ],
        outputs: [],
        sourcePath: 'projects/duxkit-ai/src/lib/chain-of-thought/chain-of-thought-step.ts',
      },
    ],
  },
  task: {
    selectors: [
      '[aiTask]',
      'ai-task',
      '[aiTaskContent]',
      'ai-task-content',
      'button[aiTaskTrigger]',
      'ai-task-trigger',
      '[aiTaskItemFile]',
      'ai-task-item-file',
      '[aiTaskItem]',
      'ai-task-item',
    ],
    exports: ['Task', 'TaskContent', 'TaskTrigger', 'TaskItemFile', 'TaskItem'],
    inputs: ['autoToggle', 'isStreaming', 'class'],
    outputs: [],
    sourcePaths: [
      'projects/duxkit-ai/src/lib/task/task.ts',
      'projects/duxkit-ai/src/lib/task/task-content.ts',
      'projects/duxkit-ai/src/lib/task/task-trigger.ts',
      'projects/duxkit-ai/src/lib/task/task-item-file.ts',
      'projects/duxkit-ai/src/lib/task/task-item.ts',
    ],
    symbols: [
      {
        name: 'Task',
        selectors: ['[aiTask]', 'ai-task'],
        inputs: [
          {
            name: 'autoToggle',
            type: 'boolean',
            defaultValue: 'true',
            required: false,
            description:
              'Automatically expands while task activity is streaming and collapses when it finishes.',
          },
          {
            name: 'isStreaming',
            type: 'boolean | undefined',
            defaultValue: 'undefined',
            required: false,
            description: 'Whether task activity is currently streaming.',
          },
          {
            name: 'class',
            type: 'string | undefined',
            defaultValue: 'undefined',
            required: false,
            description: 'Additional classes merged onto the task root element.',
          },
        ],
        outputs: [],
        sourcePath: 'projects/duxkit-ai/src/lib/task/task.ts',
      },
      {
        name: 'TaskContent',
        selectors: ['[aiTaskContent]', 'ai-task-content'],
        inputs: [
          {
            name: 'class',
            type: 'string | undefined',
            defaultValue: 'undefined',
            required: false,
            description: 'Additional classes merged onto the collapsible task content region.',
          },
        ],
        outputs: [],
        sourcePath: 'projects/duxkit-ai/src/lib/task/task-content.ts',
      },
      {
        name: 'TaskTrigger',
        selectors: ['button[aiTaskTrigger]', 'ai-task-trigger'],
        inputs: [
          {
            name: 'class',
            type: 'string | undefined',
            defaultValue: 'undefined',
            required: false,
            description: 'Additional classes merged onto the task trigger button.',
          },
        ],
        outputs: [],
        sourcePath: 'projects/duxkit-ai/src/lib/task/task-trigger.ts',
      },
      {
        name: 'TaskItemFile',
        selectors: ['[aiTaskItemFile]', 'ai-task-item-file'],
        inputs: [
          {
            name: 'class',
            type: 'string | undefined',
            defaultValue: 'undefined',
            required: false,
            description: 'Additional classes merged onto the highlighted task file element.',
          },
        ],
        outputs: [],
        sourcePath: 'projects/duxkit-ai/src/lib/task/task-item-file.ts',
      },
      {
        name: 'TaskItem',
        selectors: ['[aiTaskItem]', 'ai-task-item'],
        inputs: [
          {
            name: 'class',
            type: 'string | undefined',
            defaultValue: 'undefined',
            required: false,
            description: 'Additional classes merged onto the task item element.',
          },
        ],
        outputs: [],
        sourcePath: 'projects/duxkit-ai/src/lib/task/task-item.ts',
      },
    ],
  },
  tool: {
    selectors: [
      '[aiTool]',
      'ai-tool',
      '[aiToolContent]',
      'ai-tool-content',
      'button[aiToolTrigger]',
      'ai-tool-trigger',
      '[aiToolStatus]',
      'ai-tool-status',
    ],
    exports: ['Tool', 'ToolContent', 'ToolTrigger', 'ToolStatus'],
    inputs: ['part', 'class', 'variant'],
    outputs: [],
    sourcePaths: [
      'projects/duxkit-ai/src/lib/tool/tool.ts',
      'projects/duxkit-ai/src/lib/tool/tool-content.ts',
      'projects/duxkit-ai/src/lib/tool/tool-trigger.ts',
      'projects/duxkit-ai/src/lib/tool/tool-status.ts',
    ],
    symbols: [
      {
        name: 'Tool',
        selectors: ['[aiTool]', 'ai-tool'],
        inputs: [
          {
            name: 'part',
            type: 'AiToolPart',
            defaultValue: '-',
            required: true,
            description: 'AI SDK tool part used to derive the tool name, state, and JSON payload.',
          },
          {
            name: 'class',
            type: 'string | undefined',
            defaultValue: 'undefined',
            required: false,
            description: 'Additional classes merged onto the tool root element.',
          },
        ],
        outputs: [],
        sourcePath: 'projects/duxkit-ai/src/lib/tool/tool.ts',
      },
      {
        name: 'ToolContent',
        selectors: ['[aiToolContent]', 'ai-tool-content'],
        inputs: [
          {
            name: 'class',
            type: 'string | undefined',
            defaultValue: 'undefined',
            required: false,
            description: 'Additional classes merged onto the collapsible tool content region.',
          },
        ],
        outputs: [],
        sourcePath: 'projects/duxkit-ai/src/lib/tool/tool-content.ts',
      },
      {
        name: 'ToolTrigger',
        selectors: ['button[aiToolTrigger]', 'ai-tool-trigger'],
        inputs: [
          {
            name: 'class',
            type: 'string | undefined',
            defaultValue: 'undefined',
            required: false,
            description: 'Additional classes merged onto the tool trigger button.',
          },
        ],
        outputs: [],
        sourcePath: 'projects/duxkit-ai/src/lib/tool/tool-trigger.ts',
      },
      {
        name: 'ToolStatus',
        selectors: ['[aiToolStatus]', 'ai-tool-status'],
        inputs: [
          {
            name: 'variant',
            type: 'ToolStatusVariant',
            defaultValue: "'badge'",
            required: false,
            description: 'Presentation style for the tool status indicator.',
          },
          {
            name: 'class',
            type: 'string | undefined',
            defaultValue: 'undefined',
            required: false,
            description: 'Additional classes merged onto the tool status element.',
          },
        ],
        outputs: [],
        sourcePath: 'projects/duxkit-ai/src/lib/tool/tool-status.ts',
      },
    ],
  },
  reasoning: {
    selectors: [
      '[aiReasoning]',
      'ai-reasoning',
      '[aiReasoningContent]',
      'ai-reasoning-content',
      'button[aiReasoningTrigger]',
      'ai-reasoning-trigger',
    ],
    exports: ['Reasoning', 'ReasoningContent', 'ReasoningTrigger'],
    inputs: [
      'autoToggle',
      'isStreaming',
      'class',
      'markdown',
      'collapsedMaxHeight',
      'pinToBottom',
      'showMoreLabel',
      'showLessLabel',
    ],
    outputs: [],
    sourcePaths: [
      'projects/duxkit-ai/src/lib/reasoning/reasoning.ts',
      'projects/duxkit-ai/src/lib/reasoning/reasoning-content.ts',
      'projects/duxkit-ai/src/lib/reasoning/reasoning-trigger.ts',
    ],
    symbols: [
      {
        name: 'Reasoning',
        selectors: ['[aiReasoning]', 'ai-reasoning'],
        inputs: [
          {
            name: 'autoToggle',
            type: 'boolean',
            defaultValue: 'true',
            required: false,
            description:
              'Automatically expands while reasoning is streaming and collapses when it finishes.',
          },
          {
            name: 'isStreaming',
            type: 'boolean',
            defaultValue: 'false',
            required: false,
            description: 'Whether reasoning content is currently streaming.',
          },
          {
            name: 'class',
            type: 'string | undefined',
            defaultValue: 'undefined',
            required: false,
            description: 'Additional classes merged onto the reasoning root element.',
          },
        ],
        outputs: [],
        sourcePath: 'projects/duxkit-ai/src/lib/reasoning/reasoning.ts',
      },
      {
        name: 'ReasoningContent',
        selectors: ['[aiReasoningContent]', 'ai-reasoning-content'],
        inputs: [
          {
            name: 'markdown',
            type: 'string | undefined',
            defaultValue: 'undefined',
            required: false,
            description: 'Markdown source rendered inside the reasoning panel.',
          },
          {
            name: 'collapsedMaxHeight',
            type: 'number | string | undefined',
            defaultValue: 'undefined',
            required: false,
            description: 'Maximum collapsed content height before the show more control appears.',
          },
          {
            name: 'pinToBottom',
            type: 'boolean',
            defaultValue: 'false',
            required: false,
            description:
              'Keeps the reasoning content scrolled to the bottom when new content is appended.',
          },
          {
            name: 'showMoreLabel',
            type: 'string',
            defaultValue: "'Show more'",
            required: false,
            description: 'Accessible label for the control that expands clipped reasoning content.',
          },
          {
            name: 'showLessLabel',
            type: 'string',
            defaultValue: "'Show less'",
            required: false,
            description:
              'Accessible label for the control that collapses clipped reasoning content.',
          },
          {
            name: 'class',
            type: 'string | undefined',
            defaultValue: 'undefined',
            required: false,
            description: 'Additional classes merged onto the reasoning content element.',
          },
        ],
        outputs: [],
        sourcePath: 'projects/duxkit-ai/src/lib/reasoning/reasoning-content.ts',
      },
      {
        name: 'ReasoningTrigger',
        selectors: ['button[aiReasoningTrigger]', 'ai-reasoning-trigger'],
        inputs: [
          {
            name: 'class',
            type: 'string | undefined',
            defaultValue: 'undefined',
            required: false,
            description: 'Additional classes merged onto the reasoning trigger button.',
          },
        ],
        outputs: [],
        sourcePath: 'projects/duxkit-ai/src/lib/reasoning/reasoning-trigger.ts',
      },
    ],
  },
  sources: {
    selectors: [
      '[aiSources]',
      'ai-sources',
      '[aiSourcesContent]',
      'ai-sources-content',
      'button[aiSourcesTrigger]',
      'a[aiSource]',
    ],
    exports: ['Sources', 'SourcesContent', 'SourcesTrigger', 'Source'],
    inputs: ['class', 'count', 'href', 'title', 'target', 'rel'],
    outputs: [],
    sourcePaths: [
      'projects/duxkit-ai/src/lib/sources/sources.ts',
      'projects/duxkit-ai/src/lib/sources/sources-content.ts',
      'projects/duxkit-ai/src/lib/sources/sources-trigger.ts',
      'projects/duxkit-ai/src/lib/sources/source.ts',
    ],
    symbols: [
      {
        name: 'Sources',
        selectors: ['[aiSources]', 'ai-sources'],
        inputs: [
          {
            name: 'class',
            type: 'string | undefined',
            defaultValue: 'undefined',
            required: false,
            description: 'Additional classes merged onto the sources root element.',
          },
        ],
        outputs: [],
        sourcePath: 'projects/duxkit-ai/src/lib/sources/sources.ts',
      },
      {
        name: 'SourcesContent',
        selectors: ['[aiSourcesContent]', 'ai-sources-content'],
        inputs: [
          {
            name: 'class',
            type: 'string | undefined',
            defaultValue: 'undefined',
            required: false,
            description: 'Additional classes merged onto the collapsible sources content region.',
          },
        ],
        outputs: [],
        sourcePath: 'projects/duxkit-ai/src/lib/sources/sources-content.ts',
      },
      {
        name: 'SourcesTrigger',
        selectors: ['button[aiSourcesTrigger]'],
        inputs: [
          {
            name: 'count',
            type: 'number',
            defaultValue: '-',
            required: true,
            description: 'Number of sources referenced by the response.',
          },
          {
            name: 'class',
            type: 'string | undefined',
            defaultValue: 'undefined',
            required: false,
            description: 'Additional classes merged onto the sources trigger button.',
          },
        ],
        outputs: [],
        sourcePath: 'projects/duxkit-ai/src/lib/sources/sources-trigger.ts',
      },
      {
        name: 'Source',
        selectors: ['a[aiSource]'],
        inputs: [
          {
            name: 'href',
            type: 'string | undefined',
            defaultValue: 'undefined',
            required: false,
            description: 'URL opened when the source link is activated.',
          },
          {
            name: 'title',
            type: 'string | undefined',
            defaultValue: 'undefined',
            required: false,
            description: 'Accessible source title and default visible label.',
          },
          {
            name: 'target',
            type: 'string | undefined',
            defaultValue: "'_blank'",
            required: false,
            description: 'Anchor target for the source link.',
          },
          {
            name: 'rel',
            type: 'string | undefined',
            defaultValue: "'noreferrer'",
            required: false,
            description: 'Relationship attribute for the source link.',
          },
          {
            name: 'class',
            type: 'string | undefined',
            defaultValue: 'undefined',
            required: false,
            description: 'Additional classes merged onto the source link.',
          },
        ],
        outputs: [],
        sourcePath: 'projects/duxkit-ai/src/lib/sources/source.ts',
      },
    ],
  },
  confirmation: {
    selectors: [
      '[aiConfirmation]',
      'ai-confirmation',
      '[aiConfirmationAccepted]',
      'ai-confirmation-accepted',
      'button[aiConfirmationAction]',
      '[aiConfirmationActions]',
      'ai-confirmation-actions',
      '[aiConfirmationRejected]',
      'ai-confirmation-rejected',
      '[aiConfirmationRequest]',
      'ai-confirmation-request',
      '[aiConfirmationTitle]',
      'ai-confirmation-title',
    ],
    exports: [
      'Confirmation',
      'ConfirmationAccepted',
      'ConfirmationAction',
      'ConfirmationActions',
      'ConfirmationRejected',
      'ConfirmationRequest',
      'ConfirmationTitle',
    ],
    inputs: ['part', 'class'],
    outputs: [],
    sourcePaths: [
      'projects/duxkit-ai/src/lib/confirmation/confirmation.ts',
      'projects/duxkit-ai/src/lib/confirmation/confirmation-accepted.ts',
      'projects/duxkit-ai/src/lib/confirmation/confirmation-action.ts',
      'projects/duxkit-ai/src/lib/confirmation/confirmation-actions.ts',
      'projects/duxkit-ai/src/lib/confirmation/confirmation-rejected.ts',
      'projects/duxkit-ai/src/lib/confirmation/confirmation-request.ts',
      'projects/duxkit-ai/src/lib/confirmation/confirmation-title.ts',
    ],
    symbols: [
      {
        name: 'Confirmation',
        selectors: ['[aiConfirmation]', 'ai-confirmation'],
        inputs: [
          {
            name: 'part',
            type: 'ConfirmationToolPart',
            defaultValue: '-',
            required: true,
            description: 'AI SDK tool part containing approval state and confirmation metadata.',
          },
          {
            name: 'class',
            type: 'string | undefined',
            defaultValue: 'undefined',
            required: false,
            description: 'Additional classes merged onto the confirmation root element.',
          },
        ],
        outputs: [],
        sourcePath: 'projects/duxkit-ai/src/lib/confirmation/confirmation.ts',
      },
      {
        name: 'ConfirmationAccepted',
        selectors: ['[aiConfirmationAccepted]', 'ai-confirmation-accepted'],
        inputs: [],
        outputs: [],
        sourcePath: 'projects/duxkit-ai/src/lib/confirmation/confirmation-accepted.ts',
      },
      {
        name: 'ConfirmationAction',
        selectors: ['button[aiConfirmationAction]'],
        inputs: [],
        outputs: [],
        sourcePath: 'projects/duxkit-ai/src/lib/confirmation/confirmation-action.ts',
      },
      {
        name: 'ConfirmationActions',
        selectors: ['[aiConfirmationActions]', 'ai-confirmation-actions'],
        inputs: [
          {
            name: 'class',
            type: 'string | undefined',
            defaultValue: 'undefined',
            required: false,
            description: 'Additional classes merged onto the confirmation actions container.',
          },
        ],
        outputs: [],
        sourcePath: 'projects/duxkit-ai/src/lib/confirmation/confirmation-actions.ts',
      },
      {
        name: 'ConfirmationRejected',
        selectors: ['[aiConfirmationRejected]', 'ai-confirmation-rejected'],
        inputs: [],
        outputs: [],
        sourcePath: 'projects/duxkit-ai/src/lib/confirmation/confirmation-rejected.ts',
      },
      {
        name: 'ConfirmationRequest',
        selectors: ['[aiConfirmationRequest]', 'ai-confirmation-request'],
        inputs: [],
        outputs: [],
        sourcePath: 'projects/duxkit-ai/src/lib/confirmation/confirmation-request.ts',
      },
      {
        name: 'ConfirmationTitle',
        selectors: ['[aiConfirmationTitle]', 'ai-confirmation-title'],
        inputs: [
          {
            name: 'class',
            type: 'string | undefined',
            defaultValue: 'undefined',
            required: false,
            description: 'Additional classes merged onto the confirmation title element.',
          },
        ],
        outputs: [],
        sourcePath: 'projects/duxkit-ai/src/lib/confirmation/confirmation-title.ts',
      },
    ],
  },
  'code-block': {
    selectors: ['ai-code-block'],
    exports: ['CodeBlock'],
    inputs: ['code', 'language', 'class'],
    outputs: [],
    sourcePaths: ['projects/duxkit-ai/src/lib/code-block/code-block.ts'],
    symbols: [
      {
        name: 'CodeBlock',
        selectors: ['ai-code-block'],
        inputs: [
          {
            name: 'code',
            type: 'string',
            defaultValue: '-',
            required: true,
            description: 'Code string to render, copy, and download.',
          },
          {
            name: 'language',
            type: 'string',
            defaultValue: "'text'",
            required: false,
            description:
              'Language identifier used for syntax highlighting and file extension detection.',
          },
          {
            name: 'class',
            type: 'string | undefined',
            defaultValue: 'undefined',
            required: false,
            description: 'Additional classes merged onto the code block root element.',
          },
        ],
        outputs: [],
        sourcePath: 'projects/duxkit-ai/src/lib/code-block/code-block.ts',
      },
    ],
  },
} satisfies Record<ComponentDocSlug, ComponentApiMetadata>;
